// Supports weights 200-800
import '@fontsource-variable/oxanium';
import './globals.css'
import Navbar from './components/navbar'

export const metadata = {
  title: 'Portafolio',
  description: 'Generated by Sebastian Burgos',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  )
}
